### ISSUE TITLE
创建重复邮箱的address时的问题

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#69]
调用POST /v1/addresses接口，当设置的邮箱地址已被创建了address时，再次设置该邮箱创建address时，未给出该地址已存在的提示信息；
且当该已存在的address为deleted时，亦操作成功，返回的address id为之前已存在的address的id；

**Comment by huojiao2006** [comment]
fixed

**Comment by liuyp2018** [comment]
验证结果：
目前，创建address时，当设置的邮箱和系统中已存在的active状态的address的邮箱重复时，不能利用该邮箱创建address；
当系统中该邮箱对应的address为deleted状态时，可以再次利用该邮箱创建address。

问题已修复，关闭问题。
