### ISSUE TITLE
创建或修改address接口，设置的notify type不正确时，需优化提示信息

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#70]
调用 POST /v1/addresses接口，创建通知地址时，或者调用PUT /v1/addresses/{address id}修改address时，若设置的notify type为不正确的字段
调用失败，提示信息为：
"error": "创建资源失败: rpc error: code = InvalidArgument desc = 校验失败",

问题：提示信息未明确指出哪个字段校验失败，建议优化此提示信息

**Comment by huojiao2006** [comment]
fix

**Comment by liuyp2018** [comment]
经验证，提示信息已优化，关闭问题。
