### ISSUE TITLE
修改address接口，未添加address detail和notify_type字段时，应校验通过

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#72]
调用PUT /v1/addresses/{address id}，修改address时，body中第二个参数address detail，未添加该字段时，提示信息为：非法的Email格式[]；此参数为非必填项，当未添加该字段时，应该校验通过。
同样，notify_type字段也是非必填参数，当未添加该字段时，也应校验通过。

**Comment by huojiao2006** [comment]
fix

**Comment by liuyp2018** [comment]
经验证，问题已修复，关闭问题。
