### ISSUE TITLE
PUT /v1/addresses/{address id}接口，notify_type不正确时，需优化提示信息

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#73]
调用PUT /v1/addresses/{address id}，修改address时，设置的notify_type字段不是“email”时，提示信息为：error：校验失败

问题：提示信息不够准确，建议优化提示信息

**Comment by huojiao2006** [comment]
fix

**Comment by liuyp2018** [comment]
经验证，问题已修复，关闭问题。
