### ISSUE TITLE
删除已处于删除状态的address时，应给出address已处于删除状态的提示信息

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#74]
调用DELETE /v1/addresses/，删除已删除的address

预期结果：已删除的address，在删除时应给出该address已处于删除状态的提示信息

实际结果：未给出上述提示信息

**Comment by huojiao2006** [comment]
该接口是批量删除接口，只负责删除，不负责检查是不是已经删除，在调用之前要自己查询出需要删除的记录。

**Comment by huojiao2006** [comment]
fixed
