### ISSUE TITLE
删除address时，当address list中包含有重复的address时的问题

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#75]
调用DELETE /v1/addresses/删除address时，当address list中包含有重复的address时

预期结果1：系统内部会过滤掉重复的address，可以操作成功 
或者 
预期结果2：不能成功操作，但提出正确的提示信息：传入的address list中包含有重复的address

实际结果：调用后报错，提示地址不存在

**Comment by huojiao2006** [comment]
fix

**Comment by liuyp2018** [comment]
经验证，当address list中包含有重复的address时，系统内部会过滤掉重复的address，可以成功删除；
问题已修复，关闭问题；
