### ISSUE TITLE
删除已删除状态的addresslist时，应给出该addresslist已处于删除状态的提示信息

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#80]
调用DELETE /v1/addresslists删除已删除状态的addresslist时，未提示该addresslist已处于删除状态

**Comment by huojiao2006** [comment]
该接口是批量删除接口，只负责删除，不负责检查是不是已经删除，在调用之前要自己查询出需要删除的记录。

**Comment by huojiao2006** [comment]
fixed
