### ISSUE TITLE
删除addresslist接口，当address_list_id中包含有重复的id时，调用时提示信息不正确

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#82]
调用 DELETE /v1/addresslists删除addresslist时，当address_list_id中包含有重复的id时，提示地址列表不存在。

**Comment by huojiao2006** [comment]
fix

**Comment by liuyp2018** [comment]
在新版中验证，当addresslist id中包含又重复的addresslist时，会过滤掉重复的id，成功删除；
关闭问题。
