### ISSUE TITLE
修改addresslist接口，设置extra为字母字符串时，调用失败

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#86]
调用PUT  /v1/addresslists/{addresslist}修改addresslist时，设置extra为数字字符串时：
{
  "extra": "11"
}
可以成功操作

但设置extra为包含字母的字符串时：
{
  "extra": "aa"
}

不能成功操作，错误提示信息为：
"error": "更新资源[adl-57ZORpm996Yv]失败: Error 3140: Invalid JSON text: \"Invalid value.\" at position 0 in value for column 'address_list.extra'.",

**Comment by huojiao2006** [comment]
fixed

**Comment by liuyp2018** [comment]
经验证，问题已修复，关闭问题。
