### ISSUE TITLE
查询addresslist接口，设置extra，查询不到对应的addresslist

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#88]
系统中存在extra为{\"extra info\": \"11\"}的addresslist
在调用查询addresslist接口时，设置查询字段extra为{\"extra info\": \"11\"}，查询结果为空，查询不到对应的addresslist

**Comment by huojiao2006** [comment]
fixed

**Comment by liuyp2018** [comment]
经验证，问题已修复，关闭问题。
