### ISSUE TITLE
修改address list接口，设置各参数字段后，调用失败

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#89]
修改address list接口，设置各参数字段如下：
{
  "addresslist": "adl-8jl7gMx31gBz",
  "address_list_name": "bb"
}
调用后，失败信息如下："error": "更新资源[adl-8jl7gMx31gBz]失败: Error 1205: Lock wait timeout exceeded; try restarting transaction"

**Comment by huojiao2006** [comment]
fix

**Comment by liuyp2018** [comment]
经验证，问题已修复，关闭问题。
