### ISSUE TITLE
经常不能成功发送通知

### ISSUE THREAD

**Issue by liuyp2018** [openpitrix/notification#98]
调用创建通知接口，设置参数如下：
{
  "content_type": "invite",
  "title": "notification title",
  "content":"{\"html\":\"test_content_html\"}",
  "address_info": "{\"email\": [\"316778710@qq.com\"]}",
  "expired_days": 1,
  "available_start_time": "00:00:00",
  "available_end_time": "00:00:00"
}

调用后，查看该通知的状态，一直处于pending状态，有时为failed状态，不能成功发送通知：
{
  "total_count": 1,
  "notification_set": [
    {
      "notification_id": "nf-g7KgZ5zM4ok4",
      "content_type": "invite",
      "title": "notification title",
      "content": "{\"html\":\"test_content_html\"}",
      "short_content": "",
      "expired_days": 1,
      "status": "pending",
      "create_time": "2019-08-15T06:33:26Z",
      "status_time": "2019-08-15T06:33:26Z",
      "owner": "",
      "address_info": "{\"email\": [\"316778710@qq.com\"]}",
      "available_start_time": "00:00:00",
      "available_end_time": "00:00:00",
      "extra": "{}"
    }
  ]
}

**Comment by huojiao2006** [comment]
"available_start_time": "00:00:00",
"available_end_time": "00:00:00"
修改为有效的发送时间段即可

**Comment by liuyp2018** [comment]
修改available_start_time和available_end_time参数设置如下：
      "available_start_time": "00:00:00",
      "available_end_time": "23:59:59"

发送通知后，查询该通知，其状态一直处于pending状态：
{
      "notification_id": "nf-0X78MEJnJok4",
      "content_type": "invite",
      "title": "title-000169137",
      "content": "{\"html\":\"notification test content\", \"normal\":\"test_content_normal\"}",
      "short_content": "short_content123",
      "expired_days": 0,
      "status": "pending",
      "create_time": "2019-08-16T02:58:49Z",
      "status_time": "2019-08-16T02:58:49Z",
      "owner": "KubeSphere",
      "address_info": "{\"email\": [\"316778710@qq.com\"]}",
      "available_start_time": "00:00:00",
      "available_end_time": "23:59:59",
      "extra": "{}"
    }

**Comment by huojiao2006** [comment]
fixed
